# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b94516bd8714fc4f067fae7d08580a7936ce81f3b85f905b5ed53ddd5ea7fa8632d9d90e92f56d659705f59ab2eab910150b46d619975c61fbf7be9e53d189f3

test:
  secret_key_base: 9efe4707916ad90116600151df19daa02bfde2ec7c86eb4d7c2c98303269f3ce18f037be422797cf789f1c5aed6ef08333cdc9b4a4fcc2b036ef3a7bf5d3e67c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
